version: '3.8'
services:
  cassandra:
    hostname: cassandra
    image: cassandra:4.1.2
    volumes:
      - cassandra-volume:/var/lib/cassandra
    ports:
      - 9042:9042
      - 9160:9160
      # These are intra-node communication ports. They'll matter if this ever takes on multiple nodes
      #- 7000:7000
      #- 7001:7001
      #- 7199:7199

volumes:
  cassandra-volume:
    driver_opts:
      type: none
      device: ${BASE_DIR}/volumes/cassandra
      o: bind